# Generated by Django 3.0.3 on 2020-02-25 19:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200201_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='privileges',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Users.manageUser', 'Manage Users'), ('Sales.manage', 'Manage Sales'), ('Sales.docs', 'Manage Documents')], max_length=40, null=True),
        ),
    ]
