# Generated by Django 3.0.2 on 2020-01-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_batchfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchfile',
            name='file',
            field=models.FileField(upload_to='payments/uploads/'),
        ),
    ]
