# Generated by Django 3.0.2 on 2020-01-31 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20200131_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchfile',
            options={'ordering': ['-created_at']},
        ),
    ]
